name: Build 111 for Android

on:
  workflow_dispatch:  
  schedule:
    - cron: '0 0,12 * * *'  

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Clone repository
      run: |
        git clone --recursive ${{secrets.URL}} 111
        cd 111 && git submodule update --init --recursive
        echo "REPO_ROOT=$(pwd)" >> $GITHUB_ENV
    
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y glslang-tools vulkan-tools zip
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'
    
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
    
    - name: Install NDK and CMake
      run: |
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
          "ndk;25.2.9519653" \
          "cmake;3.22.1"
        echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk/25.2.9519653" >> $GITHUB_ENV
    
    - name: Build Android APKs
      working-directory: ${{ env.REPO_ROOT }}/src/android
      run: |
        chmod +x gradlew
        ./gradlew assembleRelWithDebInfo assemblerelease \
          -Pandroid.ndkVersion=25.2.9519653 \
          -Pandroid.cmakeVersion=3.22.1 || echo "Build may have warnings"
    

    
    - name: Upload APKs (if exist)
      uses: actions/upload-artifact@v4
      if: success() || failure()  
      with:
        name: android-apks
        path: |
          ${{ env.REPO_ROOT }}/src/android/app/build/outputs/apk/**/*.apk
        retention-days: 1

    - name: Find and list APK files
      id: find-apks
      run: |
        cd ${{ env.REPO_ROOT }}/src/android/app/build/outputs/apk
        find . -name "*.apk" -type f | while read file; do
          echo "Found APK: $file"
          echo "file_size=$(stat -c%s "$file")" >> $GITHUB_ENV
        done
        echo "apk_files=$(find . -name "*.apk" -type f | tr '\n' ' ')" >> $GITHUB_ENV
    